### ISSUE TITLE
SeasonalBot: Lovey-dovey valentines avatar!

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/branding#1]
We need an avatar the bot can use during february, with hearts for eyes and in pink and purpley hues.

**Comment by AnonGuy** [comment]
I'll work on this one today.

**Comment by neonsea** [comment]
Opinions on this design?

![valentines](https://vgy.me/Bf6zEc.png)

(Apologies, I posted this in the wrong issue earlier)

**Comment by jchristgit** [comment]
Looks great!

**Comment by heavysaturn** [comment]
That's more or less what I was thinking. Great job.

**Comment by heavysaturn** [comment]
You can probably just go ahead and PR this in.

**Comment by AnonGuy** [comment]
I know the PR's already been merged, but I'm interested to see how this logo would look with eyes that are shaped more like this:

![image](https://user-images.githubusercontent.com/25161069/49458947-cc2ef100-f7e5-11e8-908c-2fcb60dee30e.png)
