### ISSUE TITLE
Animated Valentines Logo Uses Incorrect Shades of Pink

### ISSUE THREAD

**Issue by MarkKoz** [python-discord/branding#113]
The background is `e062ca` but should be `d974bf`
The shadow is `b04a9c` but should be `ad5c98`
The upper snake is `ffccff` but should be `ffcbf4`

It's not as simple as changing the colour palette for the GIF because there are slightly different shades of the colours used at the edges of shapes to blend layers together. This is what it looks like with this approach:

![loved_up_512](https://user-images.githubusercontent.com/1515135/106508335-1d4bd580-6481-11eb-9a56-7425172ecb94.gif)

Granted, it may not be noticeable at small sizes.

**Comment by janine9vn** [comment]
@MarkKoz I remember there being some work done on this but unsure if anything was merged?

**Comment by MarkKoz** [comment]
nothing as far as i know

**Comment by MarkKoz** [comment]
@lemonsaurus why was this closed?

**Comment by lemonsaurus** [comment]
because the pull request was merged?

**Comment by lemonsaurus** [comment]
right, I see now that it doesn't affect this animated banner. but I'm not sure if anyone actually has this animation and can change it, I have no idea who made it.

**Comment by lemonsaurus** [comment]
I think it's quite hard to justify spending time recreating this icon over a minor color discrepencies. I'm tempted to just close this issue, especially given it's been inactive for over a year.

@MarkKoz do you have any objections to that?

**Comment by MarkKoz** [comment]
No objections
