### ISSUE TITLE
"star-struck" lemoji

### ISSUE THREAD

**Issue by v1nam** [python-discord/branding#114]
I would like to try implementing a lemoji with star struck eyes, useful in the case when you are delighted by an action and are surprised at the same time, it would be based on this emoji :star_struck:, I am thinking about making it similar to `lemon_hearteyes` but let me know if I can design it in a better way, here's a rough implementation
![lemon_starstruck](https://user-images.githubusercontent.com/71541684/107123728-24ca0f00-68c5-11eb-80d6-fe5ae25467ac.png)

**Comment by gustavwilliam** [comment]
Great idea! I think this would be very cool. Just remember to use the updated lemoji base, even if `:lemon_hearteyes:` doesn’t use it yet.
