### ISSUE TITLE
A winking lemoji

### ISSUE THREAD

**Issue by Vthechamp22** [python-discord/branding#116]
A lemojified version of :wink: maybe?

**Comment by gustavwilliam** [comment]
We have these two emojis already, but I personally don't have anything against adding a pure `:lemon_wink:` emoji. It would be a fun addition.
<img width="59" alt="Screenshot 2021-03-10 at 09 21 24" src="https://user-images.githubusercontent.com/65498475/110598405-ff5d4900-8181-11eb-8e0b-b3b0be66fbe8.png">

**Comment by gustavwilliam** [comment]
A pure winking lemoji has since been added.

<img width="38" alt="Screenshot 2022-10-25 at 06 37 32" src="https://user-images.githubusercontent.com/65498475/197683780-9c22f8d6-5508-4ab4-8935-8bdfe75b703c.png">
