### ISSUE TITLE
Python Discord-specific PFP for the ModMail bot

### ISSUE THREAD

**Issue by swfarnsworth** [python-discord/branding#118]
I'm writing this issue without having consulted the rest of the staff about whether or not this is something we'd want, so this issue should also be a discussion about that if anyone objects.

Currently, the PFP for the ModMail bot is generic. While most ModMail interactions are initiated by server members, we occasionally start them ourselves, and we have to introduce ourselves as "a moderator on Python Discord"; otherwise it isn't necessarily clear what is happening. I think integrating our logo into the current PFP might make it more clear at a glance that "this is an official communication with Python Discord" without making any changes to the ModMail source code.

For reference, this is what one sees if a moderator initiates contact with a user. Note that there is no indication that the communication has to do with Python Discord.
![image](https://user-images.githubusercontent.com/32915757/108573187-0959fd80-72e2-11eb-949f-c44e5df38147.png)

**Comment by jb3** [comment]
The good thing about the envelope is that it does help convey the DM nature of the bot, without people knowing what "modmail" means.

I'm curious if there is a logo design which can incoporate both icons to make it clearer.

Could the same effect be achieved through nicknames? Renaming the bot to `Python Discord ModMail` and giving it a nickname of `ModMail` in the server is probably the most clear we'd get it.

**Comment by swfarnsworth** [comment]
@jb3 Can that be done without making a new account? Would deploying the bot through a different Discord account cause any issues?

**Comment by jb3** [comment]
We can rename the account without having to create a new one. It's just done through the Developer portal.

**Comment by fisher60** [comment]
I believe something like this could be a very positive change, perhaps something that conveys both `dm/mail` as well as `Python`, although I am not a graphic designer so my input here is limited.

I also quite like the naming and nicknaming suggestion. I think that would be as clear as we could get, while leaving the name in the server streamlined and accessible.

**Comment by jb3** [comment]
We've actioned this through other means, so changing our modmail branding is not necessary.
