### ISSUE TITLE
Add Saint Patrick’s day Icon

### ISSUE THREAD

**Issue by MrKomodoDragon** [python-discord/branding#119]
We could possibly make an icon for saint patrick’s day, which is coming up soon in March.

**Comment by janine9vn** [comment]
@MrKomodoDragon You're now assigned, so feel free to work on this and open a PR. What were you thinking for the icon?

**Comment by MrKomodoDragon** [comment]
Possibly a green background, and a different sahdes of green for the sneks

**Comment by janine9vn** [comment]
This is closed by #120 . Thanks for the contribution by the way!
