### ISSUE TITLE
Change our banner to the new one

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/branding#13]
We will be changing our banner, although the new banner still doesn't have approval from Discord. We're in dialogue with them about this now.

The new banner will hopefully look roughly like this:
![image](https://user-images.githubusercontent.com/2098517/54480931-d9209f00-482e-11e9-8da4-2fdf87aa696e.png)

Once we've got approval, we will need to change our banner everywhere where the old one is featured.

- [x] Push the new banner to this repo, updating the svg and fixing alignment.
- [ ] Change the banner used on https://paste.pydis.com/
- [x] Change the banner used in the YouTube intro splash
- [x] Change the banner used on https://pydis.com
- [x] Change the banner used in various invites on our partner servers.
- [x] Change the banner used in the wallpapers on this repo.
- [ ] Change the icon used in the emoji on the server

I may have forgotten some, please leave a comment if you can think of any that aren't listed here.

**Comment by heavysaturn** [comment]
new banner design is approved by Discord. This issue is ready to be handled now.

**Comment by lemonsaurus** [comment]
Uploaded a raster version of the new banner, as well as the psd for it. Sadly the old SVG was broken (did not contain the letters PYTHON) so we don't have an SVG version of this right now... but that might be okay.

**Comment by lemonsaurus** [comment]
@scragly has uploaded an svg for the banner with alignment sorted.

**Comment by kwzrd** [comment]
This looks like something that can be closed.

Have we done `Change the banner used in various invites on our partner servers` and ` Change the icon used in the emoji on the server`?

**Comment by lemonsaurus** [comment]
we haven't done the latter, but I can do it now.

**Comment by kwzrd** [comment]
It looks like https://paste.pydis.com uses a slightly different banner than the one in this issue.

**Comment by lemonsaurus** [comment]
Added emoji, updated paste.pydis.com
