### ISSUE TITLE
RGB animated logo

### ISSUE THREAD

**Issue by AG4lyf** [python-discord/branding#137]
A draft was given by me in media-branding channel with  following content

https://cdn.discordapp.com/attachments/753252897059373066/819712051848151040/v1.gif

although it doesn't  follow the 3 second animation 5 second rest rule. it is still viable to use 7 seconds of animation saying there is nothing to focus on.

**Comment by lemonsaurus** [comment]
I guess that's okay, but can we have the animation flow diagonally instead of straight top to bottom?

**Comment by AG4lyf** [comment]
That's a great idea. 
i will open the PR with diagonal gradient.

**Comment by lemonsaurus** [comment]
GIF limitations make implementing this difficult without looking noisy and bad.
