### ISSUE TITLE
please make australian ducky

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/branding#141]
It should be upside down and be [wearing a hat.](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.tipperarylive.ie%2Fupload%2F1562673790732.jpg&f=1&nofb=1)

**Comment by gustavwilliam** [comment]
@lemonsaurus We do have this aura Australian ducky now:
![image](https://user-images.githubusercontent.com/65498475/135965212-0d8a1d5c-66f2-44a2-9c1e-a913ef1569fa.jpeg)

It's not quite wearing a hat, but I assume you'd be fine with closing this issue?

**Comment by lemonsaurus** [comment]
not really. we should replace that duck with a true blue Australian.
