### ISSUE TITLE
Add branding for Eid al-Fitr

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/branding#149]
We're interested in having branding for Eid al-Fitr.

Remember to follow the event branding instructions found here:
https://github.com/python-discord/branding/blob/main/events/README.md

**Comment by doublevcodes** [comment]
Comment because I need to comment because I'm doing this.

**Comment by Akarys42** [comment]
Hey @doublevcodes, do you want to be assigned to the issue?

**Comment by doublevcodes** [comment]
Yeah

**Comment by minalike** [comment]
Hey all, @doublevcodes are you still interested in this? I saw this message from last year: https://discord.com/channels/267624335836053506/753252897059373066/834514775575756810

I know the topic of Ramadan branding comes up fairly often. I also see you were never actually assigned to this issue.

Is this up for grabs?

**Comment by doublevcodes** [comment]
Hey @minalike 

I don't think I'll have time for this anymore. Life calls 😅. I'd be open to letting anyone else do this, although I did come up with some initial ideas in the #dev-branding channel.

**Comment by nerfelitewar** [comment]
yes ofc do it <3 
![Ramadan-Celebration](https://user-images.githubusercontent.com/80751691/161427066-99e2e866-2982-4787-8ede-3dae61f9048c.jpg)

**Comment by EitoZX** [comment]
uhm.. how about we close this issue now?
