### ISSUE TITLE
Branding for Comic Day

### ISSUE THREAD

**Issue by InvisibleOS** [python-discord/branding#159]
[Free Comic Book Day](https://en.wikipedia.org/wiki/Free_Comic_Book_Day) is on the [14th of August](https://g.co/kgs/PBZqKP) this year and we are approaching it. It is an annual promotional effort by the North American comic book industry to help bring new readers into independent comic book stores.

I think we could have a comic, retro or pop style branding for this event.
- I would like to do this

**Comment by NIRDERIi** [comment]
I think this is a great idea! I saw in the `dev-branding` channel in the python server you suggested making some sort of a banner or guild icon, which sounds great, can't wait to see your idea and icon design!

**Comment by InvisibleOS** [comment]
**How's this?**

![PyDisLogo](https://user-images.githubusercontent.com/76255686/127740935-cc1a6612-96e9-4de2-8d97-f15fb582dc34.png)
![logo_circle](https://user-images.githubusercontent.com/76255686/127740943-2895df9d-2675-40b2-afe8-8ceb4007d20a.png)

**Comment by InvisibleOS** [comment]
**How's this?**

![PyDisLogo](https://user-images.githubusercontent.com/76255686/127741444-c2f82165-b4ce-4790-ad43-1f3bed28a4cd.png)
![logo_evergreen](https://user-images.githubusercontent.com/76255686/127741447-29bc1523-4af1-42a3-946f-97cfdbb32a25.png)

**Comment by NIRDERIi** [comment]
I think it looks great!
