### ISSUE TITLE
Repository Social Media Previews

### ISSUE THREAD

**Issue by sco1** [python-discord/branding#16]
[About a month ago](https://github.blog/changelog/2019-04-16-repository-social-media-image/), GitHub introduced a feature that allows repository owners to customize the preview that gets shown for social media embeds when a repository is shared:

I chucked random logo from our branding repository onto bot to see what it looks like:
![image](https://user-images.githubusercontent.com/5323929/57496194-a7144200-729f-11e9-81ca-8a7f83def176.png)

![image](https://user-images.githubusercontent.com/5323929/57496132-67e5f100-729f-11e9-96f8-75215f44321a.png)

Pretty neat!

GitHub has made a [template](https://github.com/python-discord/bot/settings/og-template) available, is there any interest generating a few additional art assets to place on our more popular repos (or all of them)?

**Comment by lemonsaurus** [comment]
This is a good suggestion, we're looking for someone to try to come up with something specifically for this embed. Maybe it has a GitHub logo on it or something.

**Comment by jchristgit** [comment]
A great idea!!

**Comment by sco1** [comment]
Merged by #21
