### ISSUE TITLE
Role Icons!

### ISSUE THREAD

**Issue by janine9vn** [python-discord/branding#163]
We're in the Discord Beta for Role Icons! Let's make some role icons~

### Constraints/Guidelines:
- Must be a png/jpg or emoji from the server
- Cannot be animated
- Be under 256kb
- Should be at least 64x64 pixels

### Roles we'll be looking at:
- Code Jam/PyWeek/Game Jam Champions

I'd love some help with feedback and brainstorming~

**Comment by doublevcodes** [comment]
The purple Discord diamond thing could work for boosters.

**Comment by ChrisLovering** [comment]
How about this for mods?

![orange mod badge](https://user-images.githubusercontent.com/9753350/133987730-7f5d6b18-410b-4125-97f3-0f97f011d066.png)

**Comment by ChrisLovering** [comment]
maybe ducky Dave, or some other relevant ducky for helpers :D ?

**Comment by ChrisLovering** [comment]
I also like the idea of contribs getting an icon. I think if we do, we should also have a core dev icon that looks like an "upgraded" version of the contrib icon.

**Comment by Akarys42** [comment]
> I also like the idea of contribs getting an icon. I think if we do, we should also have a core dev icon that looks like an "upgraded" version of the contrib icon.

I like this idea! What about a single green cog for contrib and two light blue gears for core dev?

**Comment by ChrisLovering** [comment]
We should also think about giving the 3 Champion roles icons too. PyWeek, Game Jam and Code Jam

**Comment by ChrisLovering** [comment]
> > I also like the idea of contribs getting an icon. I think if we do, we should also have a core dev icon that looks like an "upgraded" version of the contrib icon.
> 
> I like this idea! What about a single green cog for contrib and two light blue gears for core dev?

Possibly :D
I'm bad at imagining what things may look like, so I have no opinions until I see the images lol

**Comment by jb3** [comment]
We've had a chat in admins and decided the roles to target for now are just the champion roles, we won't have an icon for moderators, helpers, media/forms team, help cooldown or lead roles. We'll discuss a contributor icon for a later date.

I'll update the issue text appropriately.

**Comment by janine9vn** [comment]
What's the reasoning for no help cooldown icon?

**Comment by jb3** [comment]
> What's the reasoning for no help cooldown icon 

We felt that people will just open channels to get an icon and the cost of moderating that sort of thing outweighs the benefit of having people assigned an icon for opening a help channel, especially since it's carried across the whole server, not just the currently active help channel for that user.

> and the contributors icon for a later date?

We're discussing with the Core Devs about whether they would like a Core Dev icon (Core Devs & Contribs will have the same icon), depending on the conclusion of that we'll update this issue or drop a message in dev-branding.

**Comment by lemonsaurus** [comment]
We've added a bunch of role icons by now, and they've found their way into this repo inside https://github.com/python-discord/branding/tree/main/icons/role_icons

Let's close this issue as this has been resolved.
