### ISSUE TITLE
Allow events across multiple years

### ISSUE THREAD

**Issue by bsoyka** [python-discord/branding#171]
Some of the current logic in `events/validation.py` doesn't allow for the end date of an event to be "before" the start date. This means we can't easily have New Year's branding start in December and end a few days into January.

This requires some changes to the validation here, and I imagine it might take some changes in the bot's branding daemon (see python-discord/bot#2035).

**Comment by lemonsaurus** [comment]
Yeah, I'd definitely like to see this change. 👍🏼
