### ISSUE TITLE
Add a ducky with a beer

### ISSUE THREAD

**Issue by PH-KDX** [python-discord/branding#187]
I'd like to contribute `:ducky_beer:` to our fine set of ducklets.
![ducky_beer_resized](https://user-images.githubusercontent.com/50588793/180072740-d1d63d3b-55d4-40be-a3e8-12cfcac24de9.png)

**Comment by lemonsaurus** [comment]
Renaming this PR - no need to bring alcoholism into this. All I see is a nice duck enjoying a cold one on a warm day.

**Comment by PH-KDX** [comment]
Good point, noted.
