### ISSUE TITLE
Animated default server icon for evergreen season

### ISSUE THREAD

**Issue by kosayoda** [python-discord/branding#19]
As part of the nitro server boosting perks, we now have animated server icons all year round. Thus, it would be nice to have a animated icon for our default server icon (the blurple one) during off-season.

Here are some ideas @lemonsaurus and I came up with:

* The sneks on the logo stick their tongue out, then retract them
* The logo spins every x seconds (y-axis / z-axis rotation)
* The logo pulses every x seconds
* The logo zooms off the canvas and comes back from the other side
* Scrolling text across the logo
* The logo drops off the canvas, then falls back down from the top
* The logo shrinks, then grows
* The two sneks split up, then rejoin
* The blurple logo moves off the canvas while official Python logo moves into the canvas, then the whole thing reverses / cycles
* A ripple across the canvas background

Get creative! Multiple animated default icons are welcome, as we can add bot functionality to cycle through / randomly pick different icons throughout the off-season.

Here's a crude animation I cooked up for inspiration-

![animated_icon](https://user-images.githubusercontent.com/41782385/59523230-55488280-8f03-11e9-9abe-e8e0f3d9a245.gif)

**Comment by kwzrd** [comment]
I would love to look into this over the weekend!

**Comment by SebastiaanZ** [comment]
Sounds good to me.

Maybe I'll try something, too, but I'm bad with graphics.

**Comment by lemonsaurus** [comment]
We have a bunch of these now. Solved!
