### ISSUE TITLE
SeasonalBot: Evergreen avatar

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/branding#2]
The bot will need an avatar for when no season is active - currently it's set up to use the same one as Python but that seems needlessly confusing. it'd be good if we could come up with one that's a little bit different. maybe a greenish one since it's evergreen?

**Comment by AnonGuy** [comment]
That sounds good, I'll see what I can do!

**Comment by neonsea** [comment]
Opinions on this design?

![valentines](https://vgy.me/Bf6zEc.png)

**Comment by neonsea** [comment]
Tried going for a greenish one - criticism?

![evergreen](https://vgy.me/OHzz5N.png)

**Comment by AnonGuy** [comment]
That looks great, nice job!
