### ISSUE TITLE
Hacktoberfest 2019

### ISSUE THREAD

**Issue by eivl** [python-discord/branding#24]
![Hacktoberfest_19_Events_620x76](https://user-images.githubusercontent.com/5323929/64254638-ca699980-ceed-11e9-9ca1-fb441a8fda3e.png)

[Hacktoberfest 2019](https://hacktoberfest.digitalocean.com/) [1] is quickly approaching, so it's time to think  branding and art assets for the event, which includes a nice thematic server icon and server banner to highlight the event on Discord. ~~In addition, it would be really cool to have a **custom PyDis t-shirt design** for the occasion as well.~~

If you think you can contribute something, please leave a comment with what you want to work on (an icon, a server banner, or maybe even something else). For more information about these things, read below.

For more interactive questions, feel free to contact `@ELA` or `@Ves Zappa` on server as well.

*[1] If you're unfamiliar with Hacktober, scroll to the end for a short description of the event.*

---

What we would like to have:

- [x] A thematic (animated?) server icon;
- [x] A thematic server banner;

Digital Ocean has provided a branding kit for the event: https://assets.digitalocean.com/hacktoberfest/hacktoberfest_2019_brand_assets.zip (direct link to a `zip` file). It contains various designs and shows the general theme of the event. It would be cool if the thing you design fits that theme.

---

## Server icon

We'd like to see a nice and thematic server icon for the event. This could be an animated icon (preferably), but a static icon is also fine, of course. We currently have four examples of animated icons; you can find them [here](https://github.com/python-discord/branding/tree/master/logos/logo_animated). Examples of static icons can be found [here](https://github.com/python-discord/branding/tree/master/logos/logo_discord) and [here](https://github.com/python-discord/branding/tree/master/logos/logo_seasonal)

**Notes:**
- If you're designing an animated logo, take into account that first frame will be used as the static icon when the server (mobile clients) / icon (desktop clients) is not in focus. So, the first frame should be presentable as a stand-alone icon. 
- For both static and animated, look at the examples above and try to upload similar formats with a similar naming convention. This will make it easier to use and reuse your files.

## Server banner

The server banner is the image that's visible above the channel list. It's very prominent and you've got a fair bit of space to play with. Do mind the margins, since the banner will cover the entire width of the channel column (and the banner will be cropped horizontally on smaller devices). I think it's probably best to use similar margins as [the three we already have.](https://github.com/python-discord/branding/tree/master/logos/logo_discord_banner)

**Note:**
- **It's very important to use the Discord dark theme background color.** Discord currently **does not support transparency** in banners (it will convert transparent layers to black) and most of our users use the dark Discord theme.

## T-Shirt

(removed)

---

### About Hacktoberfest
[Hacktoberfest](https://hacktoberfest.digitalocean.com/) — brought to you by DigitalOcean in partnership with DEV — is a month-long celebration of open source software. Maintainers are invited to guide would-be contributors towards issues that will help move the project forward, and contributors get the opportunity to give back to both projects they like and others they've just discovered. No contribution is too small — bug fixes and documentation updates are valid ways of participating.

Those who contribute at least 4 PRs to open source repositories during the month of October receive a t-shirt! Last year, over 46k folks completed the challenge, and this was a pretty popular event on our server last year so we're excited to run through it again.

**Comment by raghavpatnecha** [comment]
@SebastiaanZ I have created icons for Discord according to Hacktoberbest theme. Let me know your views on them:
[Discord_icon 2](https://github.com/raghavpatnecha/DBz-YouTube-Chrome-Extension/blob/master/img/discord_hack.png) 

[Discord_icon 1](https://github.com/raghavpatnecha/DBz-YouTube-Chrome-Extension/blob/master/img/discord_hack1.png) 

If you are fine with it I will create a Pull Request

**Comment by lemonsaurus** [comment]
these icons are

**Comment by lemonsaurus** [comment]
I'm gonna close this issue, since we actually have everything in it.
