### ISSUE TITLE
Create a blank social banner for external services.

### ISSUE THREAD

**Issue by scragly** [python-discord/branding#29]
The social banners setup for our Repos are suitable as a patterned social backdrop on external services such as Reddit. For this purpose, we should have a blank version of these to be able to be used, created from the PSD that exists:
https://github.com/python-discord/branding/tree/master/logos/social_banner

**Comment by Akarys42** [comment]
Wdym by white background @scragly? A full white background will probably look weird because of the letters that are already white.

**Comment by scragly** [comment]
I don't believe I've said anything about a white background. 

I'm asking for just the banner image with no text.

**Comment by Akarys42** [comment]
Yeah you didn't said anything about it, my brain just suck :D

**Comment by scragly** [comment]
No problems. I had to re-read my original message a few times just in case I really did say something silly.

**Comment by Akarys42** [comment]
Done in #30 :)
