### ISSUE TITLE
More lemojis!

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/branding#44]
@manusaurio expressed an interest in working on a set of lemojis. As we're removing a few generic emojis that express certain things, it would be good to start with lemojis that express these same emotions, so that we can still communicate in effectively the same way as we currently do.

## Planned emotes
- [ ] Angry cop/security guard
- [X] Blush
- [X] Pleased (based on the old one)
- [X] Expectant/Excited
- [X] Heart eyes
- [ ] Swag (based on the old one)
- [ ] Furious (based on the old one)
- [ ] Facepalm
- [x] Unamused
- [x] War paint (Python Discord colors)
- [ ] Anime sweat
- [X] Smug
- [ ] Comfy
- [X] Scared

## Suggested emotes
- [x] Sadness
- [x] Laughing with XD face.
- [x] Thinking
- [x] Fingerguns
- [x] Fingerguns with sunglasses
- [x] Grumpy
- [ ] Crying blood while grinning
- [x] Inspecting something with magnifying glass
- [ ] Lemoji that says pffffft
- [ ] Nervous and sweating
- [ ] Dabbing (please god yes)
- [x] Yelling and looking angry
- [ ] Very sceptical
- [ ] Sarcastic
- [ ] Animated excited lemoji that is clapping fast (see kyuuclapfast below)
- [x] Pika eared lemon thinking emoji
- [ ] Shocked
- [ ] Thumbs up
- [ ] :3
- [ ] Reading (studying from books)
- [ ] Superhero lemon

## Inspiration
**kyuuclapfast**
![clapmoji](https://user-images.githubusercontent.com/2098517/74423060-ed5e8900-4e4f-11ea-9790-9ed1d6eb5654.gif)

**Comment by AG4lyf** [comment]
Lemon doing a thoubs up , or Pat Pat

**Comment by lemonsaurus** [comment]
This was suggested in meta: 
![image](https://user-images.githubusercontent.com/2098517/75526199-9c36c380-5a11-11ea-8362-96e3cbab1a59.png)

**Comment by mbaruh** [comment]
Suggesting one with a closed/zipped/taped mouth

**Comment by lemonsaurus** [comment]
Plenty of lemojis now, let's close this.
