### ISSUE TITLE
Re-organize branding

### ISSUE THREAD

**Issue by kwzrd** [python-discord/branding#45]
# Abstract

I would like to propose that `branding` is cleaned up a little bit, and in particular the `logos` directory is re-organized to something easier to navigate for both humans and bots. I introduce two possible approaches for reducing the current complexity of showing Seasonalbots which icons to load.

# Rationale

As we've been adding more and more logos, banners and other branding features over the past months, it feels that `branding` has become a bit of a mess that is difficult to make sense of, both us and for Seasonalbot too. In particular, under [logos](https://github.com/python-discord/branding/tree/master/logos), we have sub-directories such as `logo_animated` (server icons for the off-season), but both animated and static icons for specific seasons are hidden under `logo_seasonal`, which contains further sub-directories with varying / inconsistent structure.

I've now started to work on https://github.com/python-discord/organisation/issues/202, which aims to simplify Seasonalbot's internal structure. One of the bot's responsibilities is handling seasonal branding (i.e. its own name, icon and the server icon), which we've agreed should remain after the de-seasonification (@lemonsaurus correctly points out that this is a **key pydisism**). A few months back, @sco1 pointed out that the way this is done is sub-optimal, as the bot uses hard-coded paths to the branding repository in order to download specific icons: [see here](https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/season.py#L85). This creates a burden of having to reflect any changes in seasonal branding by adjusting the paths, which requires cross-repository adjustments, and feels fairly fragile.

I vowed to alleviate this by introducing automatic icon discovery, however how successful such a system can be will depend partly on the structure of `branding`.

# Proposal

Regardless of approach taken, I propose that a new sub-directory is created, called `seasonal` or similar. This will contain a sub-directory for each season, including `off-season` (perhaps calling this `evergreen` as we do in some places is better - these are the icons that we "fall back on" when no season is active). Each season (how exactly we'll represent this in Seasonalbot is still up for discussion) will then be matched to exactly one such sub-directory.

Then, to allow more sophisticated branding handling from Seasonalbot, we can take either of the following approaches.

### Approach 1

Within each season, we shall have `banner`, `server_icon` and `bot_icon` sub-dirs. The bot will look here to grab icons. The individual names of icons will then (in some way) reflect their filesize (which to pick shall again be configured in Seasonalbot):

├── branding/
│   ├── seasonal/
│   │   ├── evergreen/
│   │   │   ├── banner/
│   │   │   │   ├── banner.png
│   │   │   ├── bot_icon/
│   │   │   │   ├── bot_icon.png
│   │   │   ├── server_icon/
│   │   │   │   ├── python_512.png
│   │   │   │   ├── python_256.png
│   │   │   │   ├── python_64.png
│   │   ├── christmas/
│   │   │   ├── ...

One problem this does not account for is the branding changing yearly. For example, under [christmas](https://github.com/python-discord/branding/tree/master/logos/logo_seasonal/christmas), we already have specific branding for 2018 and 2019. We can only expect this to be more and more prevalent as time goes on. Introducing another layer, i.e. `branding/seasonal/christmas/2020/...` would add more depth to the hierarchy, and it would require "maintenance" work each year, plus if the branding doesn't change, it may have to be duplicated in multiple sub-dirs.

The implementation of "naively" constructing the paths feels like a bit of a nightmare.

### Approach 2

Depending purely on the paths may end up being very restrictive and introduce more problems than it solves. An alternative, which would allow much more flexibility, while still cutting down on the maintenance debt of having to reflect branding changes in the Seasonalbot repo, is having some configuration file for each season kept directly in `branding`.

For example, with could have a `json` as follows:

```json
{
    "christmas": {
        "banner": "/logos/logo_seasonal/christmas/2019/banner.png",
        "server_icons": [
            "/logos/logo_seasonal/christmas/2019/festive_256.gif"
        ],
        "bot_icon": null
    }
}
```

There would be either **one file for each season**, or **one file for all seasons**. Before downloading an icon, the bot would simply grab this file from a hard-coded path in this repo and update its paths from it.

The pros here should be obvious: we have a lot more flexibility in how we structure the repo, we can allow for arrays (i.e. multiple icons for one season - cycle or draw randomly), we can allow for nulls (i.e. fall-back on `evergreen`) and we don't naively try to hit paths based on configured params such as `size` - all this is safely configured here, transparent, and easy to debug. The implementation in Seasonalbot would be fairly trivial and less bug-prone than approach 1.

The con is that we still need to update the paths whenever branding changes. However, **the paths can now be updated directly within the `branding` repo**, so a single PR that adds a new icon can also add or adjust the path. I believe that this pretty much entirely addresses the problem of maintaining paths in another repository.

# Conclusion

When I started to write this issue, I was fairly impartial as to which approach will be taken (or if we'll do something entirely different). The more I think about this, however, approach 1 seems like a nightmare whereas approach 2 sounds very sensible. I'll be happy to hear what anyone may have to say about this. We can also touch on it during the staff meet tonight.

**Comment by lemonsaurus** [comment]
I'm actually leaning towards approach 1 here, because it's simple and straight forward and I don't know how much of that flexibility we really need.

I would simplify the structure you suggested even further, since there's quite a few folders that are fairly superfluous. For example

```
├── branding/
│ ├── seasonal/
│ │ ├── christmas/
│ │ │ ├── icons/
│ │ │ │ ├── snowing.gif
│ │ │ │ ├── bells.gif
│ │ │ │ ├── santa.png
│ │ │ ├── misc/
│ │ │ │ ├── banner_2018.png
│ │ │ │ ├── santa_256.png
│ │ │ │ ├── santa_512.png
│ │ │ ├── banner.png
│ │ │ ├── bot_icon.png 
```

all the icons we want to rotate will be in icons, banner and bot_icon should always be at root, and anything else in the folder (such as the `misc` folder, but there might be other folders if this makes sense) is just ignored.

**Comment by kwzrd** [comment]
@lemonsaurus I like this a lot, it's fairly different from my vision of approach 1. The only downside is that in order to make adjustments, we will need to move the files themselves, rather than some sort of a reference. But that's ok.

If no one else has any suggestions, I'd be happy to go with this.

**Comment by MarkKoz** [comment]
@lemonsaurus So you propose to dump all other resolutions of images into a `misc` folder? Sounds like it could get messy. How would you handle something like [this](https://github.com/python-discord/branding/tree/master/logos/logo_seasonal/pride_animated), which has lots of files?

**Comment by lemonsaurus** [comment]
@MarkKoz hmm, no, that's not quite what I meant. `misc` is just an example. Since the implementation would ignore all other folders apart from `icons`, we could easily have additional folders and subfolders structured however we wanted. it might be a good idea to have a `misc` folder (or some other name) at the top level, for sake of consistency, but inside that folder we could do whatever we needed to.

**Comment by kwzrd** [comment]
Since no one else has commented, I went ahead and made a [new branch](https://github.com/python-discord/branding/tree/seasonal-structure) where I will transition towards the schema outlined by @lemonsaurus. For now, I only copied over evergreen / off-season assets for SeasonalBot.
