### ISSUE TITLE
SeasonalBot: Easter icon

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/branding#5]
We've decided to do an Easter season during April, which means we need you guys to make a yellowish Python icon we can use during that season. For the eyes, perhaps something like bunny eyes?

![image](https://user-images.githubusercontent.com/2098517/53561344-ebbc8800-3b4e-11e9-978d-d50b18576696.png)

**Comment by SebastiaanZ** [comment]
Bunny ears on our snakes could be recognizable as well.

**Comment by heavysaturn** [comment]
might be okay. we'd probably have to run it by the PSF though, since it "makes major changes the shape of the icon"

**Comment by heavysaturn** [comment]
Regular eyes.

**Comment by lemonsaurus** [comment]
This one is completed.
