### ISSUE TITLE
SeasonalBot: Pride icon

### ISSUE THREAD

**Issue by AnonGuy** [python-discord/branding#6]
We'll need a pride-themed icon for June. It could have a rainbow flag blackground, or a scheme that matches one of the many pride flags:
![image](https://user-images.githubusercontent.com/25161069/53697565-59281d00-3dca-11e9-9507-b22a43f3eb5b.png)

**Comment by heavysaturn** [comment]
I personally would love to see many of these rendered in logo format so we could switch the icon out every 5th day or so.

**Comment by kosayoda** [comment]
Resolved by #17
