### ISSUE TITLE
logos/logo_discord/logo_discord.svg is looking.. droopy.

### ISSUE THREAD

**Issue by heavysaturn** [python-discord/branding#7]
![image](https://user-images.githubusercontent.com/2098517/53869664-f072b780-3ff8-11e9-8394-a4d98a57c214.png)

not sure what happened to this one, but it should be fixed.

**Comment by scragly** [comment]
It's just having a tough time man. It'll work itself out.

**Comment by scragly** [comment]
Resolved with https://github.com/python-discord/branding/commit/c961ae91b1642bf05ca80499b4cebd4eed29f367

Accidentally merged to master though, sorry.
