### ISSUE TITLE
Cowboy lemoji, please.

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/branding#75]
Can 🤠 we please 🤠  have a cowboy 🤠  lemoji? 🤠

**Comment by Xithrius** [comment]
I shall practice more when I have time, sorry for this late response.

**Comment by saiTama-max** [comment]
uhm i tried....
![image](https://user-images.githubusercontent.com/71541684/99513364-91153080-29b0-11eb-97e7-98b5635977d8.png)

**Comment by gustavwilliam** [comment]
@saiTama-max Thanks for giving this a shot. I'm not a huge fan of how the hat looks. It's not symmetrical and it's closer to one eyebrow than the other. Are we sure we even want leaves under the hat? Just some things to keep in mind.

Also, in the future, try to get assigned to the issue before working on it. Most importantly, it signals that someone is working on it and ensures that multiple people aren't at the same time. Do you want me to assign you to this issue?

**Comment by saiTama-max** [comment]
Ah no, I just wanted to try it

**Comment by Shivansh-007** [comment]
I 🤠 would 🤠 like 🤠 to 🤠 work 🤠 on 🤠 this!

**Comment by Kronifer** [comment]
@Senjan21 I would like to take this

**Comment by Senjan21** [comment]
> @Senjan21 I would like to take this

I have assigned you. Have fun with the design!

**Comment by Kronifer** [comment]
Thanks! 🤠
