### ISSUE TITLE
Update lemojis with updated lemoji template

### ISSUE THREAD

**Issue by janine9vn** [python-discord/branding#76]
Current lemojis are not updated to use the most recent symmetrical + perfectly masked lemoji template currently in the branding repo. This issue would require someone to go to through and update all svgs and pngs to use that new template. 

I don't believe it should require an update to the emojis on the server as they are small enough to not notice the slight masking issues and not perfect symmetry. But this update should help when using these assets in other branding projects (i.e. videos + animated gifs).

**Comment by janine9vn** [comment]
I can also work on this today if someone wants to assign this to me.

**Comment by gustavwilliam** [comment]
If you decide to do go through and update all of them, I think updating the emojis on the server would be reasonable as well. It doesn't require more than a couple of seconds.

**Comment by lemonsaurus** [comment]
I think this was solved back in the day. Closing it.
