### ISSUE TITLE
Angrily-sad lemoji 

### ISSUE THREAD

**Issue by Atharv-Attri** [python-discord/branding#84]
I wish to design a new lemoji that has an expression of being angry and sad at the same time.  This would be useful because many times people are very angry about something, but they are also sad about that very thing (You can't honestly say you have never experienced that feeling). Currently, I expect it would be a merge of :lemon_enraged:, :lemon_grumpy:, and :lemon_pensive:.

**Comment by gustavwilliam** [comment]
I think this would be great. Assigning you to it now.

**Comment by Atharv-Attri** [comment]
Thanks!

**Comment by lemonsaurus** [comment]
sounds fine to me. go ahead.

**Comment by gustavwilliam** [comment]
This was closed by #110.
