### ISSUE TITLE
Better streaming camframes

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/branding#85]
When we do various streams for the community, we often build frame assets that we can use for the streams.

For example, here are the ones I'll be using for the Summer Code Jam 2020

![lemonframe](https://user-images.githubusercontent.com/2098517/95085034-f4a80f00-071e-11eb-8eea-9acfbce514b5.png)
![ves camframe](https://user-images.githubusercontent.com/2098517/95085040-f70a6900-071e-11eb-8b8c-7d445e6b3ccb.png)
![joe camframe](https://user-images.githubusercontent.com/2098517/95085042-f8d42c80-071e-11eb-99db-1a7a4ade8372.png)

_(The image inside the frame is where the webcam feed would be displayed, and is just a placeholder)_

These frames are pretty boring. For some code jams, we've created custom frames to suit the theme, for example here is the Ancient Tech stream frame:
![image](https://user-images.githubusercontent.com/2098517/95085149-1ef9cc80-071f-11eb-99d9-30537436be78.png)

None of these frames are in this repo (shame on me), and we should honestly maybe make some better _templates_. All the frames I've made are also raster, and we should probably do this in vector and add the SVGs here.

**Comment by gustavwilliam** [comment]
In this issue, are we looking for completely new frames or updating the ones you provided to match the theme?

**Comment by lemonsaurus** [comment]
both. either. We're going to do lots of streaming, and we will need frames for these streams. It'd be nice to have some options.

The end goal is to have a folder in this repo with some streaming assets, including several different kinds of frames.

**Comment by gustavwilliam** [comment]
Alright, sounds good!

**Comment by lemonsaurus** [comment]
Not really relevant anymore now that we're using Streamyard
