### ISSUE TITLE
GIL Emoji

### ISSUE THREAD

**Issue by janine9vn** [python-discord/branding#86]
We need a GIL emoji! What does this look like? Well... here's a few elements to start with:
- Lock
- "GIL"
- Python Logo

Possible implementation:
- GILectomy (GIL lock being removed from the python logo)

**Comment by lemonsaurus** [comment]
I don't know. Do we? The GILectomy is such a pie in the sky at this stage, if it's ever gonna happen it's probably years away.

I guess I'd be okay with a Python logo with a lock on it or something to represent the GIL, but I'm not sure it'd see much use.

**Comment by lemonsaurus** [comment]
Closing this, never seemed to materialize.
