### ISSUE TITLE
okhandbutflipped blurry not identical to default emoji

### ISSUE THREAD

**Issue by fisher60** [python-discord/branding#90]
## Issue
The `okhandbutflipped` emoji is not identical to the default `ok_hand` emoji.

## Summary
When viewed side-by-side it is clear that the flipped emoji is a little blurry, as well as being thicker and generally different enough that a few users complained about it.

![image](https://user-images.githubusercontent.com/39353605/95729048-1f1f2e00-0c31-11eb-8a41-ae2571a4c13b.png)

**Comment by gustavwilliam** [comment]
Unless there's any design decision from the original designer to consider, I could fix this.

**Comment by jb3** [comment]
Twemoji updated the hand and we didn't which is why the design is different. Go for it @gustavwilliam.

**Comment by gustavwilliam** [comment]
Perfect; that's what I had expected.
