### ISSUE TITLE
Summer Code Jam 2020 Highlights

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/branding#95]
For the Winter Code Jam, we created a highlights video, which you can find here: 
https://www.youtube.com/watch?v=8fbZsGrqBzo

The video consists of footage from the 10 finalists, a voiceover by yours truly, an intro sequence, and some lowerthirds created in After Effects.

Creating a video like this can be a bit labor intensive, so we're looking for contributors who are willing to help out with part of this process. The most immediate need is the recording of footage for the video.

I'm happy to record the voice-over for the video, and I've still got the intro sequence and the lowerthirds stored on my local machine, so I'd be happy to handle these tasks. That still leaves a few other tasks:
- Recording footage from each of the 10 projects, including audio.
- Editing that footage together into a cohesive, continuous clip.
- Writing a script for the voiceover.

If you'd like to help out with one or all of these three tasks, please leave a comment and let us know.

**Comment by gustavwilliam** [comment]
I'd probably be able to help out with writing the script and brainstorming ideas for the video

**Comment by janine9vn** [comment]
I'm happy to help with recording footage from the projects and also assisting in editing the footage together in a cohesive, continuous clip. While doing this I can also take notes for the voiceover to help with the script writing portion. 

What's the timeline look for this? Is there a specific date you'd like this to be released?

**Comment by lemonsaurus** [comment]
No specific date, the sooner the better but no real rush. Right now, I'm building some acoustic absorber panels for my studio, a project that will probably still take me a few more weeks. After that I will be able to record a far better voice-over, so I'd say we at least have a few weeks to get the footage and script ready.

**Comment by gustavwilliam** [comment]
Do we have any approximate length that we'd like the video to have? Generally on YouTube, these are my observations and data from previous research regarding optimal video length and time:
- Total: 11 min (±3 min)
- Intro: 1 min 10 s (±20 s)

Something like this would probably be quite good for this as well. We should also try to add some fun or almost surprising elements at times. This will help keep the interest up.

**Comment by janine9vn** [comment]
Longer content does tend to work well in my experience. It's just that most content creators go for maximum value with minimum time and that tends to be on the 12-15 minute range. 

Maybe a few ducky appearances?

**Comment by gustavwilliam** [comment]
For sure. We should definitely have quite a few duckies in there. 12–15 minutes would be fine with me for this.

**Comment by lemonsaurus** [comment]
I think 12-15 minutes sounds about right.

**Comment by lemonsaurus** [comment]
Please also keep in mind that this is something we aim to do twice a year, so let's try to come up with a format and a process that isn't a ton of work so that we can keep it up consistently.

Which is to say - don't wear yourself out, and look for ways to generalize an approach. Maybe we can make some lower thirds with duckies in them that can be reused for all videos. Maybe we can make some nice ducky transitions that we can re-use. A good template for the script. Sound effects, music, .. let's build a kit that we can use to make this trivial next time.

**Comment by lemonsaurus** [comment]
We've set some rough deadlines now for this task:
- First draft of script should be done by 8th of November, handled by @gustavwilliam
- Voiceover + music should be done by 15th of November, handled by @lemonsaurus 
- Rough cut of video should be finished by 22nd of November, handled by @janine9vn 
- Polish and sound effects should be done by 29th of November, @lemonsaurus will take the lead but we'll handle this as a group.

**Comment by gustavwilliam** [comment]
Here are a few of the things we discussed earlier today.
### Video ideas
- Order projects "last to first" in the rank they got
- Include "honorable mentions" projects as well
- Start with a hook that wants them to watch until the end
- Presentations of projects should generally be < 1 minute, but should vary based on the size and interest of each project
- Duckies "sprinkled into the project" and as transitions
- Sharp transitions and title screens to keep it interesting

### About the process
- Present "snippet" of video and what is thought to be included before finishing
- Finish (first draft of) script before video, so the video can be fitted to the script
- Create transitions, processes and similar things that could be used when making future videos as well

**Comment by lemonsaurus** [comment]
* First draft of script by 20th of November (@gustavwilliam and @janine9vn)
* Voiceover + music by 22th of November (@lemonsaurus)
* Rough cut of video by 6th of December (@janine9vn)
* Final cut by 13th of December (@lemonsaurus)

**Comment by lemonsaurus** [comment]
Voiceover is complete:
https://cdn.discordapp.com/attachments/753252897059373066/785156110343864450/Summer_Code_Jam_2020_Highlights-_Voiceover.mp3

**Comment by lemonsaurus** [comment]
Completed. see the final video at https://www.youtube.com/watch?v=g9cnp4W0P54
